apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-web-cliente
  namespace: web-cliente
spec:
  rules:
  # Tu dominio profesional y amigable para el SEO
  - host: tienda.ukiyocazorla.es
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: service-web-cliente
            port:
              number: 80