name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:

  build-and-push:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Login en DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Construir imagen Docker
        run: |
          docker build \
          -t bmleon/webcliente:${{ github.sha }} \
          -t bmleon/webcliente:latest \
          -f deploy/Dockerfile .

      - name: Subir imagen a DockerHub
        run: |
          docker push bmleon/webcliente:${{ github.sha }}
          docker push bmleon/webcliente:latest