apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-panel-admin
  namespace: web-cliente
  labels:
    app: panel-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: panel-admin
  template:
    metadata:
      labels:
        app: panel-admin
    spec:
      containers:
      - name: panel-admin
        image: bmleon/ukiyo-admin:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: NUXT_PUBLIC_API_BASE
          value: "https://ukiyocazorla.es"
        # 🌟 ESTO ES LO QUE DESPIERTA A ARGOCD Y FUERZA LA DESCARGA DE LA IMAGEN NUEVA
        - name: FORCE_RESTART_FECHA
          value: "03-Sep-2026_17-38"
          value: "01-Sep-2026_21-52"
          value: "01-Sep-2026_21-42"
          value: "15-Aug-2026_21-16"
          value: "11-Aug-2026_22-03"
          value: "11-Aug-2026_21-25"
          value: "31-Jul-2026_17-48"
          value: "31-Jul-2026_17-40"
          value: "31-Jul-2026_17-35"
          value: "14-Jun-2026_10-10"
          value: "14-Jun-2026_10-04"
          value: "14-Jun-2026_09-58"
          value: "14-Jun-2026_09-52"
          value: "13-Jun-2026_06-54"
          value: "13-Jun-2026_06-51"
          value: "13-Jun-2026_06-35"
          value: "13-Jun-2026_06-24"
          value: "13-Jun-2026_06-19"
          value: "13-Jun-2026_06-13"
          value: "13-Jun-2026_06-08"
          value: "12-Jun-2026_18-58"
          value: "12-Jun-2026_18-46"
          value: "12-Jun-2026_18-25"
          value: "12-Jun-2026_18-19"
          value: "12-Jun-2026_18-16"
          value: "12-Jun-2026_18-09"
          value: "07-Jun-2026_21-22"
          value: "07-Jun-2026_21-21"
          value: "07-Jun-2026_21-10"
          value: "07-Jun-2026_21-05"
          value: "06-Jun-2026_18-06"
          value: "06-Jun-2026_18-04"
          value: "06-Jun-2026_17-52"
          value: "05-Jun-2026_07-40"
          value: "05-Jun-2026_07-34"
          value: "04-Jun-2026_14-25"
          value: "04-Jun-2026_12-27"
          value: "04-Jun-2026_09-59"
          value: "04-Jun-2026_07-51"
          value: "04-Jun-2026_07-39"
          value: "04-Jun-2026_07-22"
          value: "03-Jun-2026_18-39"
          value: "03-Jun-2026_18-31"
          value: "03-Jun-2026_18-12"
          value: "03-Jun-2026_17-40"
          value: "03-Jun-2026_17-28"
          value: "03-Jun-2026_10-34"
          value: "03-Jun-2026_10-21"
          value: "03-Jun-2026_10-12"
          value: "03-Jun-2026_09-52"
          value: "03-Jun-2026_07-46"
          value: "03-Jun-2026_07-39"
          value: "03-Jun-2026_07-29"
          value: "02-Jun-2026_22-34"
          value: "02-Jun-2026_22-06"
          value: "02-Jun-2026_21-57"
          value: "02-Jun-2026_21-42"
          value: "02-Jun-2026_21-23"
          value: "02-Jun-2026_16-58"
          value: "02-Jun-2026_11-16"
          value: "02-Jun-2026_11-06"
          value: "02-Jun-2026_11-00"
          value: "02-Jun-2026_10-53"
          value: "02-Jun-2026_10-42"
          value: "02-Jun-2026_10-29"
          value: "02-Jun-2026_09-53"
          value: "02-Jun-2026_09-43"
          value: "02-Jun-2026_09-23"
          value: "02-Jun-2026_09-15"
          value: "02-Jun-2026_07-55"
          value: "02-Jun-2026_07-52"
          value: "02-Jun-2026_07-47"
          value: "02-Jun-2026_07-42"
          value: "02-Jun-2026_07-34"
          value: "01-Jun-2026_18-57"
          value: "01-Jun-2026_18-44"
          value: "01-Jun-2026_18-37"
          value: "01-Jun-2026_18-29"
          value: "01-Jun-2026_18-29"