apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-panel-admin
  namespace: web-cliente
  labels:
    app: panel-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: panel-admin
  template:
    metadata:
      labels:
        app: panel-admin
    spec:
      containers:
      - name: panel-admin
        image: bmleon/ukiyo-admin:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: NUXT_PUBLIC_API_BASE
          value: "https://ukiyocazorla.es"
        # 🌟 ESTO ES LO QUE DESPIERTA A ARGOCD Y FUERZA LA DESCARGA DE LA IMAGEN NUEVA
        - name: FORCE_RESTART_FECHA
          value: "02-Jun-2026_22-34"
          value: "02-Jun-2026_22-06"
          value: "02-Jun-2026_21-57"
          value: "02-Jun-2026_21-42"
          value: "02-Jun-2026_21-23"
          value: "02-Jun-2026_16-58"
          value: "02-Jun-2026_11-16"
          value: "02-Jun-2026_11-06"
          value: "02-Jun-2026_11-00"
          value: "02-Jun-2026_10-53"
          value: "02-Jun-2026_10-42"
          value: "02-Jun-2026_10-29"
          value: "02-Jun-2026_09-53"
          value: "02-Jun-2026_09-43"
          value: "02-Jun-2026_09-23"
          value: "02-Jun-2026_09-15"
          value: "02-Jun-2026_07-55"
          value: "02-Jun-2026_07-52"
          value: "02-Jun-2026_07-47"
          value: "02-Jun-2026_07-42"
          value: "02-Jun-2026_07-34"
          value: "01-Jun-2026_18-57"
          value: "01-Jun-2026_18-44"
          value: "01-Jun-2026_18-37"
          value: "01-Jun-2026_18-29"
          value: "01-Jun-2026_18-29"