pipeline {
    agent {
        kubernetes {
            yaml '''
            apiVersion: v1
            kind: Pod
            spec:
              containers:
              - name: kaniko
                image: gcr.io/kaniko-project/executor:debug
                command: ["sleep"]
                args: ["9999999"]
              - name: kubectl
                image: bitnami/kubectl:latest
                command: ["sleep"]
                args: ["9999999"]
            '''
        }
    }

    environment {
        // Tus datos exactos sacados de tus YAML
        DOCKER_USER = 'bmleon'
        IMAGE_NAME = 'miportfolio' 
    }

    stages {
        stage('Construir y Subir (Kaniko)') {
            steps {
                container('kaniko') {
                    // Usamos las credenciales que ya tienes en Jenkins
                    withCredentials([usernamePassword(credentialsId: 'docker-hub-creds', passwordVariable: 'DOCKER_PASS', usernameVariable: 'DOCKER_USER_VAR')]) {
                        sh '''
                        echo "Configurando credenciales para Kaniko..."
                        mkdir -p /kaniko/.docker
                        echo "{\\"auths\\":{\\"https://index.docker.io/v1/\\":{\\"username\\":\\"${DOCKER_USER_VAR}\\",\\"password\\":\\"${DOCKER_PASS}\\"}}}" > /kaniko/.docker/config.json

                        echo "Empaquetando tu portfolio..."
                        /kaniko/executor --context `pwd` --dockerfile `pwd`/Dockerfile --destination ${DOCKER_USER}/${IMAGE_NAME}:latest
                        '''
                    }
                }
            }
        }

        stage('Desplegar en Kubernetes') {
            steps {
                container('kubectl') {
                    echo 'Aplicando todos tus archivos YAML de la carpeta kubernetes...'
                    sh 'kubectl apply -f deploy/kubernetes/'

                    echo 'Reiniciando el deployment para asegurar que coge la imagen más nueva...'
                    sh 'kubectl rollout restart deployment deploy-miportfolio -n namespace-miportfolio'
                }
            }
        }
    }
}