pipeline {
    agent {
        kubernetes {
            yaml '''
            apiVersion: v1
            kind: Pod
            spec:
              containers:
              - name: docker-client
                image: docker:24-cli
                command: ['cat']
                tty: true
              - name: docker-daemon
                image: docker:24-dind
                securityContext:
                  privileged: true
                env:
                - name: DOCKER_TLS_CERTDIR
                  value: ""
            '''
        }
    }

    environment {
        DOCKER_IMAGE = "bmleon/miportfolio:latest"
        PROJECT_DIR  = "Docker/proyectos/mi_Portfolio"
        DOCKER_HOST  = "tcp://localhost:2375"
    }

    stages {
        stage('Construir y Subir Imagen') {
            steps {
                container('docker-client') {
                    script {
                        // Esperamos a que el motor de Docker esté listo
                        echo "Iniciando motor Docker..."
                        sh 'while ! docker info >/dev/null 2>&1; do sleep 2; done'
                        
                        dir("${PROJECT_DIR}") {
                            echo "Construyendo la imagen..."
                            sh "docker build -t ${DOCKER_IMAGE} -f deploy/Dockerfile ."
                            
                            echo "Subiendo imagen a Docker Hub..."
                            withCredentials([usernamePassword(credentialsId: 'docker-hub-creds', passwordVariable: 'DOCKER_PASS', usernameVariable: 'DOCKER_USER')]) {
                                sh "echo \$DOCKER_PASS | docker login -u \$DOCKER_USER --password-stdin"
                                sh "docker push ${DOCKER_IMAGE}"
                            }
                        }
                    }
                }
            }
        }
    }

    post {
        success { 
            echo "✅ ¡Imagen construida y subida con éxito a Docker Hub!" 
        }
        failure { 
            echo "❌ Error en el Pipeline. Revisa los logs." 
        }
    }
}